name: ${project.name}
main: net.daboross.bukkitdev.commoncommands.CommonCommands
version: ${project.version}
author: Dabo Ross
description: Common Commands For Newlanders!
commands:
  w:
    description: Gets your current location and world
    usage: /<command>
    aliases: [whereami, wai]
  wi:
    description: Gets the location and world of a given player
    usage: /<command> <Player>
    aliases: [whereis]