name: ${project.name}
main: net.daboross.bukkitdev.ncommon.NCommonPlugin
version: ${project.version}
author: Dabo Ross
description: ${project.description}
commands:
  w:
    aliases: [whereami, wai]
  wi:
    aliases: [whereis]